### ISSUE TITLE
No specified license

### ISSUE THREAD

**Issue by ghost** [aronj/CFGGameConfigurationSyntax#1]
You probably want to add a license to this project. Why? [See this article by GitHub](https://help.github.com/articles/open-source-licensing/). I'm working on creating a derivative of this (converting the bundle to be compatible with Atom) but I don't think I am -- legally speaking -- allowed to.

I personally recommend the [MIT license](https://opensource.org/licenses/MIT) because it's permissive and very simple, but there's a lot of options. [Here's a great site](http://choosealicense.com/) to help you pick.

**Comment by aronj** [comment]
Unfortunately I don't know if I'm permitted either. :/
If I am, I see no reason to be able to pick MIT as well.

**Comment by ghost** [comment]
I see, so this is derivative work as well? If it is, you should be able to use whichever license the original author used if they specified one.

**Comment by aronj** [comment]
71984001c054a192345464f6cbc73dcc16af3aa0 there we go :)

**Comment by ghost** [comment]
That's awesome, cheers!
